// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiCore.Lib.DAL;

namespace WikiCore.Lib.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181031063049_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497");

            modelBuilder.Entity("WikiCore.Lib.DAL.Model.WikiPageEntity", b =>
                {
                    b.Property<string>("Slug")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<string>("Title");

                    b.Property<int>("Version");

                    b.HasKey("Slug");

                    b.ToTable("WikiPages");
                });
#pragma warning restore 612, 618
        }
    }
}
